from enum import Enum


class State(int, Enum):
    START = 0
    LOCATION = 1
    FIND_LOCATION = 2
    FIND_ADDRESS = 3
    FIND_CURRENT = 4
    NO_LOCATION = 5
    AUTO_SELECT = 6
    SELECT_LOCATION = 7
    RETURN_LOCATION = 8
    POST_RETURN_LOCATION = 9
    REQUEST_SCHEDULE = 10
    CREATE_SCHEDULE = 11
    ASK_EVENT = 12
    ASK_TIME = 13
    CREATING_SCHEDULE = 14
    ROUTE = 15
    ASK_PLACE = 16
    FIND_ROUTE = 17
